//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardTTS.LocalTest {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ARSWHSuri.org/", ConfigurationName="LocalTest.LMMS_WebserviceSoap")]
    public interface LMMS_WebserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ARSWHSuri.org/LotRegister", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DashboardTTS.LocalTest.LotRegisterResponse LotRegister(DashboardTTS.LocalTest.LotRegisterRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://ARSWHSuri.org/LotRegister", ReplyAction="*")]
        System.Threading.Tasks.Task<DashboardTTS.LocalTest.LotRegisterResponse> LotRegisterAsync(DashboardTTS.LocalTest.LotRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ARSWHSuri.org/MrpLotDebug", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MrpLotDebug(string SystemID, string MachineID, string JobID, string Operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ARSWHSuri.org/MrpLotDebug", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MrpLotDebugAsync(string SystemID, string MachineID, string JobID, string Operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ARSWHSuri.org/MrpLotInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DashboardTTS.LocalTest.MRP_SearchResult MrpLotInfo(string SystemID, string MachineID, string JobID, string Operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ARSWHSuri.org/MrpLotInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<DashboardTTS.LocalTest.MRP_SearchResult> MrpLotInfoAsync(string SystemID, string MachineID, string JobID, string Operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ARSWHSuri.org/LocalTest_MrpLotInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DashboardTTS.LocalTest.MRP_SearchResult LocalTest_MrpLotInfo(string JobID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ARSWHSuri.org/LocalTest_MrpLotInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<DashboardTTS.LocalTest.MRP_SearchResult> LocalTest_MrpLotInfoAsync(string JobID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LotRegister", WrapperNamespace="http://ARSWHSuri.org/", IsWrapped=true)]
    public partial class LotRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ARSWHSuri.org/", Order=0)]
        public string SystemID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ARSWHSuri.org/", Order=1)]
        public string MachineID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ARSWHSuri.org/", Order=2)]
        public string JobID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ARSWHSuri.org/", Order=3)]
        public string Operation;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ARSWHSuri.org/", Order=4)]
        public string Message;
        
        public LotRegisterRequest() {
        }
        
        public LotRegisterRequest(string SystemID, string MachineID, string JobID, string Operation, string Message) {
            this.SystemID = SystemID;
            this.MachineID = MachineID;
            this.JobID = JobID;
            this.Operation = Operation;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LotRegisterResponse", WrapperNamespace="http://ARSWHSuri.org/", IsWrapped=true)]
    public partial class LotRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ARSWHSuri.org/", Order=0)]
        public bool LotRegisterResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ARSWHSuri.org/", Order=1)]
        public string Message;
        
        public LotRegisterResponse() {
        }
        
        public LotRegisterResponse(bool LotRegisterResult, string Message) {
            this.LotRegisterResult = LotRegisterResult;
            this.Message = Message;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ARSWHSuri.org/")]
    public partial class MRP_SearchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool isCorrectResultField;
        
        private string statusField;
        
        private string messageField;
        
        private MRP_SearchResult_TravellerData travellerDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool isCorrectResult {
            get {
                return this.isCorrectResultField;
            }
            set {
                this.isCorrectResultField = value;
                this.RaisePropertyChanged("isCorrectResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MRP_SearchResult_TravellerData TravellerData {
            get {
                return this.travellerDataField;
            }
            set {
                this.travellerDataField = value;
                this.RaisePropertyChanged("TravellerData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ARSWHSuri.org/")]
    public partial class MRP_SearchResult_TravellerData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemField;
        
        private string descriptionField;
        
        private decimal inQuantityField;
        
        private string startOnField;
        
        private string lotnoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal InQuantity {
            get {
                return this.inQuantityField;
            }
            set {
                this.inQuantityField = value;
                this.RaisePropertyChanged("InQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StartOn {
            get {
                return this.startOnField;
            }
            set {
                this.startOnField = value;
                this.RaisePropertyChanged("StartOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Lotno {
            get {
                return this.lotnoField;
            }
            set {
                this.lotnoField = value;
                this.RaisePropertyChanged("Lotno");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LMMS_WebserviceSoapChannel : DashboardTTS.LocalTest.LMMS_WebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LMMS_WebserviceSoapClient : System.ServiceModel.ClientBase<DashboardTTS.LocalTest.LMMS_WebserviceSoap>, DashboardTTS.LocalTest.LMMS_WebserviceSoap {
        
        public LMMS_WebserviceSoapClient() {
        }
        
        public LMMS_WebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LMMS_WebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LMMS_WebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LMMS_WebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DashboardTTS.LocalTest.LotRegisterResponse DashboardTTS.LocalTest.LMMS_WebserviceSoap.LotRegister(DashboardTTS.LocalTest.LotRegisterRequest request) {
            return base.Channel.LotRegister(request);
        }
        
        public bool LotRegister(string SystemID, string MachineID, string JobID, string Operation, ref string Message) {
            DashboardTTS.LocalTest.LotRegisterRequest inValue = new DashboardTTS.LocalTest.LotRegisterRequest();
            inValue.SystemID = SystemID;
            inValue.MachineID = MachineID;
            inValue.JobID = JobID;
            inValue.Operation = Operation;
            inValue.Message = Message;
            DashboardTTS.LocalTest.LotRegisterResponse retVal = ((DashboardTTS.LocalTest.LMMS_WebserviceSoap)(this)).LotRegister(inValue);
            Message = retVal.Message;
            return retVal.LotRegisterResult;
        }
        
        public System.Threading.Tasks.Task<DashboardTTS.LocalTest.LotRegisterResponse> LotRegisterAsync(DashboardTTS.LocalTest.LotRegisterRequest request) {
            return base.Channel.LotRegisterAsync(request);
        }
        
        public string MrpLotDebug(string SystemID, string MachineID, string JobID, string Operation) {
            return base.Channel.MrpLotDebug(SystemID, MachineID, JobID, Operation);
        }
        
        public System.Threading.Tasks.Task<string> MrpLotDebugAsync(string SystemID, string MachineID, string JobID, string Operation) {
            return base.Channel.MrpLotDebugAsync(SystemID, MachineID, JobID, Operation);
        }
        
        public DashboardTTS.LocalTest.MRP_SearchResult MrpLotInfo(string SystemID, string MachineID, string JobID, string Operation) {
            return base.Channel.MrpLotInfo(SystemID, MachineID, JobID, Operation);
        }
        
        public System.Threading.Tasks.Task<DashboardTTS.LocalTest.MRP_SearchResult> MrpLotInfoAsync(string SystemID, string MachineID, string JobID, string Operation) {
            return base.Channel.MrpLotInfoAsync(SystemID, MachineID, JobID, Operation);
        }
        
        public DashboardTTS.LocalTest.MRP_SearchResult LocalTest_MrpLotInfo(string JobID) {
            return base.Channel.LocalTest_MrpLotInfo(JobID);
        }
        
        public System.Threading.Tasks.Task<DashboardTTS.LocalTest.MRP_SearchResult> LocalTest_MrpLotInfoAsync(string JobID) {
            return base.Channel.LocalTest_MrpLotInfoAsync(JobID);
        }
    }
}
